### ISSUE TITLE
Plugin report 

### ISSUE THREAD

**Issue by 1640946640** [RonanPlugins/BetterRTP#171]
**Plugin Version**:

**Describe The Bug**:

**How To Reproduce**:

**Expected Behavior**:

**Screenshots/Error Log**:

**Additional Context**:

java.lang.NoSuchMethodException: java.lang.NoClassDefFoundError: org/kingdoms/manager/game/GameManagement
[16:24:41] [Server thread/WARN]:        at catserver.server.remapper.target.ReflectionMethods.getMethod(ReflectionMethods.java:92)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.references.depends.regionPlugins.RTP_Residence.check(RTP_Residence.java:16)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPPluginValidation.checkLocation(RTPPluginValidation.java:14)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.checkDepends(RTPPlayer.java:121)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.attempt(RTPPlayer.java:89)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.lambda$randomlyTeleport$0(RTPPlayer.java:71)
[16:24:41] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
[16:24:41] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source)
[16:24:41] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.thenAccept(Unknown Source)
[16:24:41] [Server thread/WARN]:        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPPlayer.lambda$randomlyTeleport$1(RTPPlayer.java:69)
[16:24:41] [Server thread/WARN]:        at com.tcoded.folialib.impl.SpigotImplementation.lambda$runNextTick$0(SpigotImplementation.java:36)
[16:24:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[16:24:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421)
[16:24:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894)
[16:24:41] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
[16:24:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
[16:24:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
[16:24:41] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by SuperRonanCraft** [comment]
@TechnicallyCoded Reflection is all you bud, any idea what could be wrong?

**Comment by TechnicallyCoded** [comment]
Readable logs: https://mclo.gs/yO0W3c4
Will review this

**Comment by TechnicallyCoded** [comment]
Ok, that's not a reflection that we even do.. especially not from the residence hook.

**Comment by TechnicallyCoded** [comment]
@1640946640 provide **full server logs** of this happening on the newest version of all plugins.
