### ISSUE TITLE
Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously

### ISSUE THREAD

**Issue by ddsb520** [RonanPlugins/BetterRTP#199]
**Plugin Version**:
3.6.12
**Describe The Bug**:
can't add effects to player?
**How To Reproduce**:
add this plugin in Folia(MC:1.20.4)
**Expected Behavior**:
fix this bug
**Screenshots/Error Log**:
Here's the console output that I think is useful
`[21:47:21 INFO]: Chunky27 issued server command: /brtp
[21:47:22 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1151) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1146) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1137) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:513) ~[luminol-1.20.4.jar:git-Lum
inol-"5e79b7c"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:507) ~[luminol-1.20.4.jar:git-Lum
inol-"5e79b7c"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:521) ~[luminol-1.20.4.jar:git-Lu
minol-"5e79b7c"]
        at me.SuperRonanCraft.BetterRTP.player.rtp.effects.RTPEffect_Potions.lambda$giveEffects$0(RTPEffect_Potions.java:65) ~[BetterRTP-3.6
.12.jar:?]
        at me.SuperRonanCraft.BetterRTP.lib.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:38) ~[BetterRTP-
3.6.12.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[lumi
nol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j
ar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"5e79b7c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"5e79b7c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"5e79b7c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`
 **Additional Context**:
#195

**Comment by Yomamaeatstoes** [comment]
> **Plugin Version**: 3.6.12 **Describe The Bug**: can't add effects to player? **How To Reproduce**: add this plugin in Folia(MC:1.20.4) **Expected Behavior**: fix this bug **Screenshots/Error Log**: Here's the console output that I think is useful `[21:47:21 INFO]: Chunky27 issued server command: /brtp [21:47:22 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously java.lang.Throwable: null at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c"] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1151) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1146) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1137) ~[?:?] at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:513) ~[luminol-1.20.4.jar:git-Lum inol-"5e79b7c"] at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:507) ~[luminol-1.20.4.jar:git-Lum inol-"5e79b7c"] at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:521) ~[luminol-1.20.4.jar:git-Lu minol-"5e79b7c"] at me.SuperRonanCraft.BetterRTP.player.rtp.effects.RTPEffect_Potions.lambda$giveEffects$0(RTPEffect_Potions.java:65) ~[BetterRTP-3.6 .12.jar:?] at me.SuperRonanCraft.BetterRTP.lib.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:38) ~[BetterRTP- 3.6.12.jar:?] at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[lumi nol-1.20.4.jar:?] at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179 ) ~[luminol-1.20.4.jar:?] at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.j ar:?] at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"5e79b7c "] at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar :git-Luminol-"5e79b7c"] at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4. jar:git-Luminol-"5e79b7c"] at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j ar:git-Luminol-"5e79b7c"] at java.lang.Thread.run(Thread.java:1583) ~[?:?]` **Additional Context**: #195

Please build the latest BetterRTP Version

**Comment by TechnicallyCoded** [comment]
Inactive
