### ISSUE TITLE
Random error occur in folia

### ISSUE THREAD

**Issue by cgw2023** [RonanPlugins/BetterRTP#213]
**Plugin Version**:

[BetterRTP] Version #3.6.12

**Describe The Bug**:

random error message shown when server is running
```
[22:34:47 ERROR]: Thread Region Scheduler Thread #15 failed main thread check: Cannot add effects to entities asynchronously
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1170) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1165) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1156) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:529) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:523) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:537) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at me.SuperRonanCraft.BetterRTP.player.rtp.effects.RTPEffect_Potions.lambda$giveEffects$0(RTPEffect_Potions.java:65) ~[BetterRTP-3.6.12.jar:?]
	at me.SuperRonanCraft.BetterRTP.lib.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:38) ~[BetterRTP-3.6.12.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**How To Reproduce**:

No steps

**Expected Behavior**:

No errors

**Screenshots/Error Log**:

![image](https://github.com/RonanPlugins/BetterRTP/assets/136877036/bd371619-5d5b-4518-914e-6895ff8626d2)

**Additional Context**:

folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf

**Comment by Yomamaeatstoes** [comment]
> **Plugin Version**:
> 
> [BetterRTP] Version #3.6.12
> 
> **Describe The Bug**:
> 
> random error message shown when server is running
> 
> ```
> [22:34:47 ERROR]: Thread Region Scheduler Thread #15 failed main thread check: Cannot add effects to entities asynchronously
> java.lang.Throwable: null
> 	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1170) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1165) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1156) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:529) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:523) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:537) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at me.SuperRonanCraft.BetterRTP.player.rtp.effects.RTPEffect_Potions.lambda$giveEffects$0(RTPEffect_Potions.java:65) ~[BetterRTP-3.6.12.jar:?]
> 	at me.SuperRonanCraft.BetterRTP.lib.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:38) ~[BetterRTP-3.6.12.jar:?]
> 	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.4.jar:?]
> 	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
> 	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
> 	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
> 	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```
> 
> **How To Reproduce**:
> 
> No steps
> 
> **Expected Behavior**:
> 
> No errors
> 
> **Screenshots/Error Log**:
> 
> ![image](https://private-user-images.githubusercontent.com/136877036/331252106-bd371619-5d5b-4518-914e-6895ff8626d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjI1NTAsIm5iZiI6MTcxNTkyMjI1MCwicGF0aCI6Ii8xMzY4NzcwMzYvMzMxMjUyMTA2LWJkMzcxNjE5LTVkNWItNDUxOC05MTRlLTY4OTVmZjg2MjZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNTA0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWRlYTI5YTIwOWNmYTk5MmVjMDE4NjkzZTBkZWQ1Y2M1ZmMzNzgyZTdmMGNlODkxMDJhZjc3YTJmNmE3YjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RgQct0nT1oJY1oyQm8fBcZbSI1fn5l3lBrTwRXSvZ-Y)
> 
> **Additional Context**:
> 
> folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf

This issue should be fixed in the latest version. Please compile BetterRTP from GitHub

**Comment by ARR4NN** [comment]
This issue has been resolved and updated to spigot.
